### ISSUE TITLE
[FEAT] - Add a meme command

### ISSUE THREAD

**Issue by LandonLloyd** [nhcarrigan/BeccaBot#255]
# Feature Request
The feature is a meme command. When you call the command a programming meme will come up in an embed. 
## Is your feature request related to a problem? Please describe:
No it is just a cool idea. 

## Describe the solution you'd like
Maybe an array of memes and each time you call the command it generates a new meme.

**Comment by nhcarrigan** [comment]
What's the plan to approach this? Uploading images manually will take a LOT of storage and Heroku will not like that. Is there an API you're aware of that we can use - while also ensuring that the memes returned are family friendly?

**Comment by LandonLloyd** [comment]
What about just links? Then people can submit there own links and add to the command a lot easier.

**Comment by nhcarrigan** [comment]
That means validating there are no duplicates, as well.

**Comment by Vyvy-vi** [comment]
I have a meme command on my bot.
but like it's python so I just pick from https://meme-api.herokuapp.com/gimme
Now this isn't per say nsfw checked... but you can select a subreddit by adding gimme/{subreddit} 
and choose an sfw page

You can look up the API source here: https://github.com/D3vd/Meme_Api

**Comment by LandonLloyd** [comment]
Do you think a link option could work? It would take some checking to make sure you don't get any duplicates but I see it as the best option, for me at least, I don't know anything about API's.

**Comment by Vyvy-vi** [comment]
well this randomises from all of reddit's meme subs so might not be duplicated

**Comment by nhcarrigan** [comment]
I think we will hold off on this for now - memes are an absolute pain to curate, and I'd rather not use an API that might risk returning something offensive.

**Comment by Vyvy-vi** [comment]
If a meme command is implemented in the future...
Another thing that can be maybe done(in a much safer way) would be to make a meme-creator command instead of a meme command. (This just fetches meme-image templates, which can be filled with top text and bottom text by the user).
The advantages of this over meme-fetchers:
1- It can be moderated(the text entered by the user would be indicative of what would be in the meme, thus making it just like moderating usual text)
2- It will be 100% sfw(as most meme maker apis just use harmless images like some cat, etc.)
3- There won't be any worries of meme freshness/duplication as these are made on the spot by text from the user
4- You may not even need to use an API to do this, you could just have a folder/links of images and add text using something like jimp or similar libraries.

An example of such memes: 

![one does not](https://user-images.githubusercontent.com/62864373/98460026-71b72000-21c6-11eb-80a7-87c80c80d79b.jpeg)

(then again... this is similar to using discord gifs... but this gives more customised text as mostly you never find the right gif)
